services:
  db:
    image: mariadb:11.7.2
    container_name: ${PROJECT_NAME}-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: ${PROJECT_NAME}-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${PROJECT_NAME}-db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wp-data:/var/www/html
    ports:
      - "${PORT}:80"

volumes:
  db-data:
    name: ${PROJECT_NAME}-db
  wp-data:
    name: ${PROJECT_NAME}-wp
